### ISSUE TITLE
Black Abishai soak

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#696] opened 2021-03-14 16:02 UTC
Black Abishai should have soak 2 like other abishai. Even the White Abishai, of a lower CR, has soak 2. Now, it could be that the white was meant to have only soak 1, in which case they should be corrected.

**Comment by mlenser** [comment] 2021-03-14 16:21
Soak is not based on challenge. It is based on natural armor, of which the Black Abishai only has 2. White Abishai has 5.

Soak is based on natural armor in an automatic way. If there are certain creatures who have a flavor reason to have a higher soak then I can customize them.

**Comment by mlenser** [comment] 2021-03-15 12:18
Closing this as it is working as intended.

**Closed by mlenser** 2021-03-15 12:18 UTC
Labels: Monsters, invalid
