### ISSUE TITLE
An illusion spell that copies other spells

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#198] opened 2020-05-11 17:53 UTC
I was thinking about Phantom Steed in Deceit (issue #191) and as this similar to Find Steed, I remembered there was some illusion spells in 3.5/Pathfinder that could copy other spells. They are Shadow Evocation and Shadow Conjuration, and could replicate the lessened effect of another spell.

So, I propose a copy of Archival Magic from Divination into Deceit, and move Phantom Steed to Spirit, since its horse is more of a Shadowfax than a mere image.

What do you think?

**Comment by DalenWBrauner** [comment] 2020-05-11 18:06
Wouldn't the caster of the Deceit version of Archival Magic need to know something about the spell they're hoping to replicate? The Divination version allows them to call to mind _anything_ within the spell limit, which makes sense- they're summoning knowledge.
Is the Deceit version intended more like deceitful "bluffing" or like illusory "copying"?

**Comment by mlenser** [comment] 2020-05-11 19:01
> move Phantom Steed to Spirit, since its horse is more of a Shadowfax than a mere image.

Spirit has nothing to do with semi-illusions. Spirit would be a terrible choice for summoning a horse. Shadow would be a much better choice. The spell is an illusion spell in RAW. So it needs to be reflavored to move elsewhere. So please either reflavor it or let it be.
__________________________

Can you write up what you think the Deceit spell should do? I'm not quite grasping how it's different from Archival Magic. Or is it a pure copy?

**Comment by Marcloure** [comment] 2020-05-12 09:37
It would be a pure copy, but thinking again I don't know if it's a good idea. Feel free to close the issue if you don't see value in it

**Comment by mlenser** [comment] 2020-05-12 09:40
I'm not opposed, just asking you to flesh out the wording of it.

**Comment by Marcloure** [comment] 2020-05-12 09:55
> **Replicate Spell** (Illusory Spell, Mirror Spell?)
> As an action, you cast an illusory replica one spell that costs 2 or less mana from any theme. The illusory spell applies its effects as normal.
> **Augment**
> The spell can cost or be augmented 1 additional mana for each additional mana expended.

**Issues:**
- It's actually a bit weaker than Archival Magic, since with Archival Magic your learn the spell for the duration, but I don't think you can learn a spell with Deceit.
- It's weird to replicate something like Resurrection or Charm Person, so maybe should only duplicate spells from the Primal power source (and name the spell something like Mimic Nature?)
- Maybe the spell should change the save of the original spell to a Will saving throw.

**Comment by DalenWBrauner** [comment] 2020-05-12 13:58
I understand how you could conceivably replicate the means of how a spell was cast and make it happen that way, but the idea of the produced spell actually being illusory in any way makes... just about zero sense to me. Illusory healing? Illusory telekenesis? The physical force field that prevents lava from getting closer is "actually an illusion"?
(This is the problem I had with an "illusory" steed that can also lift things. Because then it's not an illusion- it's some other manifestation of magic with maybe an illusion draped over it.)

**Comment by Marcloure** [comment] 2020-05-12 14:04
Some illusions in D&D can be as real as reality, I believe it just means the effect is ephemeral or unreal to someone with a sharp mind. But I agree with your other points about telekenesis and such, that is why there were only Shadow Evocation and Shadow Conjuration spells back in 3.5, I think.

**Comment by DalenWBrauner** [comment] 2020-05-12 14:09
In other words, the "deceit" part of the spell should be in how the spell is obtained, not in how it's cast.
As written, your character still somehow divines a spell, and then attempts to cast a physical version of it that is powered by illusion. If you can make that work and make sense, definitely go for it- I just don't see it.

I would instead lean into the "copycat" concept of Deceit. This may sound like a spellthief, but we're not "stealing" anything- just making a mimicry.

> As an action, you replicate the casting of a spell with your illusions, bringing you the means to cast it.
Choose a spell that you have witnessed someone cast since your last long rest. You do not need to know the spell's name or precisely how it functions- only to observe the caster. You learn that spell for the duration.

We can further differentiate the spell by, say, granting it a longer duration (e.g. until a long rest).

**Comment by DalenWBrauner** [comment] 2020-05-12 14:14
> Some illusions in D&D can be as real as reality, I believe it just means the effect is ephemeral or unreal to someone with a sharp mind

I definitely think this _can_ make sense! There's an illusory dragon spell that has a breath weapon. You can convince someone they're taking fire damage, or you can use magic to conjure actual fire. I'm generally on board with either of those concepts, but  it gets weird to me when you start affecting physical objects (lifting things, preventing passage. etc). An illusory bridge is typically thought of as "a fake bridge you mistake for being real", not something you can actually cross. Illusions by design are rarely physical, unless they are very, _very_ advanced.

**Comment by Marcloure** [comment] 2020-05-12 14:20
> As written, your character still somehow divines a spell

It's not that the caster divines the spell, they think of an effect and creates an illusion of it. "I'll create a illusion of fire exploding and burning everyone there", then procedes to create an illusion of that, which is translated as a fireball. Maybe the description could be changed to:

> As an action, you create an illusory effect that replicates one spell that costs 2 or less mana from any theme. The illusory effect applies the spell's effects as normal.

Anyway, as I said before, it's a hard spell to make here, since there isn't a clear way to say that you can only replicate spells that have a physical nature.

**Comment by DalenWBrauner** [comment] 2020-05-12 15:06
> they think of an effect and creates an illusion of it. "I'll create a illusion of fire exploding and burning everyone there"

Hmm.. but they can't just think of any old effect, right? It would have to be an existing spell. So if the illusion they create has to precisely follow the same strict rules as the normal version of an existing spell... isn't that just spellcasting?

I think this would be a lot easier to justfiy from an illusionist at a higher mana cost. It's such an advanced form of illusion magic that it can effectively replicate the real effects of any spell... even the ones that are harder to believe.
This seems a bit out of league for casters with a mana limit of 2, so I'd propose this as maybe a 4 mana spell. It would have the same effects as Archival Magic augmented to 4 mana- it just wouldn't be available to those lower tiers.

**Comment by mlenser** [comment] 2020-05-12 15:31
I agree with Dalen about most what he wrote here. I think to make this work:
- The spell needs to be high mana. Illusions that become real are high level. Illusory Dragon is probably under-leveled at 3 mana
- The spell needs to specify which themes work. Even at high level I don't see illusory healing working.

**Comment by DalenWBrauner** [comment] 2020-05-12 15:35
I think the Power Sources that make the most sense to be copied are Primal and (the current version of) Harmonic. But we may have to narrow it down more finely than by Power Source...

**Comment by Marcloure** [comment] 2020-05-12 15:38
> The spell needs to specify which themes work. Even at high level I don't see illusory healing working.

I completely agree with that. I even wrote it on my listed issues up above:

> It's weird to replicate something like Resurrection or Charm Person, so maybe it should only duplicate spells from the Primal power source (and name the spell something like Mimic Nature), or from set themes (elemental themes, creation, force, etc. The list can get quite long).

**Comment by DalenWBrauner** [comment] 2020-05-12 15:48
Beast is the only theme that feels weird to me from the Primal power source. Giving yourself gills, improving your ability to climb... with illusion magic? I don't think that makes much sense.
But even the Water theme lets you purify water of poisons and disease. Hrmm.

Maybe this just needs to be limited to spells that deal damage. Or we create a new spell that can deal a damage type of the caster's choice via illusions? But I'm not sure why that wouldn't be psychic damage, unless we're at the same tier as Illusory Dragon.

Let's phrase the question this way: What kind of spell effects do we think make sense to be achieved through illusion? What spell effects definitely don't make sense? Would some spell effects make more sense at higher mana costs / augments?

**Comment by Marcloure** [comment] 2020-05-12 15:55
The issues with this spell is what made me give up on it after some thought. It has too many variables that would probably lead to some universal damaging spell that I don't think Deceit wants.

**Comment by mlenser** [comment] 2020-05-12 18:13
Closing this as it seems there isn't a clear path forward without significant work which maybe isn't worth it.

If you think its worth it feel free to comment with a proposed direction.

**Closed by mlenser** 2020-05-12 18:13 UTC
Labels: Spells
