### ISSUE TITLE
Revisit amount of Psychic Redoubt?

### ISSUE THREAD

**Issue by DalenWBrauner** [mlenser/kryx-rpg-issues#293] opened 2020-05-27 04:16 UTC
Currently, the Psionicist gains Temp HP equal to the amount of Psi they spend. After the 5 mana change and recent upgrades to the amount of Temp HP offered by certain spells, I was curious if this amount deserved a revisit. I know the amount should stay low, but as it stands, it seems... paltry.
> **Psychic Redoubt** (_2nd_)
> You can draw vigor from the psionic energy you expend. Immediately after you spend psi, you gain temporary hit points equal to the amount of psi you spent, up to your psi limit.

**Comment by Marcloure** [comment] 2020-05-27 05:26
I mentioned it on #132. See what Kryx answered there!

**Comment by mlenser** [comment] 2020-05-27 05:41
Duplicate of #132. Feel free to continue the discussion on #132 if you think otherwise to what I wrote there.

**Closed by mlenser** 2020-05-27 05:41 UTC
Labels: duplicate
