### ISSUE TITLE
Restraining spell changes/additions

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#623] opened 2020-11-29 08:02 UTC
[Chains of Light](https://www.kryxrpg.com/themes/spells/chains-of-light)
[Constricting Bandage](https://www.kryxrpg.com/themes/spells/constricting-bandage)
[Ensnare](https://www.kryxrpg.com/themes/spells/ensnare)

All of these cost 1 mana and restrain a creature for 1 minute (concentration).  The minor problems I noticed are:
- Ensnare deals 1d6 piercing every turn, CB deals 1d6 bludgeoning, CoL deals no damage
- Ensnare and CB allow another creature to help, but CoL doesn't
- The effect is pretty generic (restraining and damage) but is currently only available in Divine and Primal; would be nice to add it to more themes if it's thematic.

My suggestions:
1. Add the following line to Chains of Light, to make it unique and a bit more competitive compared to the others (it's the same as the effect in [the Pathfinder spell](https://www.d20pfsrd.com/magic/all-spells/c/chains-of-light/)):  
> While held by the golden chains, a creature cannot move or travel using teleportation or by extradimensional or interplanar means.
2. Create a new spell, mechanically identical to CB (restrain+bludgeoning), in the Creation theme:  "Chain Bindings", which is described as:
> As an action, you conjure iron chains that wrap around a creature that you can touch or see within 60 feet. The target must make a Reflex saving throw or be restrained by the magical chains. If the target succeeds on the save, the chains dissipate.
(could also flavor this as ropes, bars, clamps, etc)

**Comment by mlenser** [comment] 2020-11-29 18:15
- Bindings added as a duplicate of Cocoon to the Creation theme
- Chains of Light now does a small amount of damage each turn
- Ensnare damage increased to 1d8 and an augment is added so it can target multiple creatures
- Constricting Bandage damage increased to 1d8 and an augment is added so it can target multiple creatures

**Closed by mlenser** 2020-11-29 18:15 UTC
Labels: Spells, enhancement
