### ISSUE TITLE
Misty Escape is a harmful feat

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#803] opened 2021-05-22 23:21 UTC
https://www.kryxrpg.com/feats/misty-escape

At first glance, this feat seems good since it means you almost never die from direct damage, but in reality, it has a lot more of downsides:

- You have to always be carrying a coffin up and down (maybe leave it at the tavern in every city you go)
- You need to always be able to reach your coffin within 2 hours
- It seems you can't be healed back up if you drop to 0 health
- If you drop to 0 hp in sunlight, you are insta-killed

Considering all this, even the benefit of the feat (becoming an almost invunerable fog when you drop to 0 hp) is actually detrimental, since then you are forced to exit the dungeon. The feat is also a major weight for the entire group, suddenly everyone has to go back to base because this one player dropped to 0 hp and can't be brought back up. 

Overall, this feat seems to do more bad than good (not even just a bad option, but straight up harmful).

While it being a feat means people can just not pick it, the **Vampiric Suffused** gains it as a class feature, but I think they might not want to have this.

**Comment by mlenser** [comment] 2021-05-23 12:05
This featr comes directly from the vampire monster:

![image](https://user-images.githubusercontent.com/235857/119259344-21396a00-bbce-11eb-9492-8fcea2b5ddd3.png)


> You have to always be carrying a coffin up and down (maybe leave it at the tavern in every city you go)

Resting place doesn't need to be a coffin.

> You need to always be able to reach your coffin within 2 hours

Same as vampire

> It seems you can't be healed back up if you drop to 0 health

fixed to work like vampire which allows it to be healed

> If you drop to 0 hp in sunlight, you are insta-killed

Same as vampire. This feels mostly fine.

__________

It seems like the main complaint is the impact on the party which is caused by the inability to be healed back up. Fixed that. Feel free to discuss more if you think something else should be fixed.

**Comment by Marcloure** [comment] 2021-05-23 12:14
> Resting place doesn't need to be a coffin.

What can be considered a resting place then?

**Comment by Marcloure** [comment] 2021-05-24 12:31
So, there are still some issues with it:

First, if you carry your coffin when you turn into mist, the coffin turns with you (it's an item you are carrying). This is just a minor bug, but it's funny to think the vampire would implode.

Second, a creature in Misty Escape takes 1 minute to revert after being healed. This basically takes them out of combat once they drop to 0 health, even if they are healed back up. It's also weird to think that until they had this feat, they could rejoin combat like everyone else.

To solve this second issue, I think that either Misty Escape given by the feat should be optional, or it should take 1 round to revert (so a creature would still lose their next turn like everyone else).

**Comment by mlenser** [comment] 2021-05-24 15:54
Reverting takes 1 minute for Gaseous Form (& Wind Walk), Wind Walk potion, Aqueous Form, Corrosive Form.

It doesn't take any time for Wild Shape, Tree Shape, Fuse Flesh, Vampires, Ssurran Shaman, Drow Arachnomancer, Archdruid, Shifter, Changeling, Mutagen from Mutant Alchemist.

I'll need to align these.

**Comment by Marcloure** [comment] 2021-05-24 16:13
Gaseous Form and Aqueous Form are out of combat spells, they are used for exploration, traevel, and infintration, so it's ok for them to take a while to revert.

**Comment by mlenser** [comment] 2021-05-27 16:06
Aqueous Form, Corrosive Form, Gaseous Form, Misty Escape, and Wind Walk potion no longer take 1 minute to revert to your normal form.

**Closed by mlenser** 2021-05-27 16:06 UTC
Labels: Feats
