### ISSUE TITLE
Regenerate multi targets

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#281] opened 2020-05-24 07:38 UTC
Regenerate spell augment:
> • You can increase the healing by 4d8 for each additional mana expended.
> 
> • You can expend 1 additional mana to target one additional creature for each additional mana expended. The creatures must be within 30 feet of each other when you target them.

Same issue with increasing targets and then scaling damage of damaging spells.

Personally, I don't think this spell should allow multitargets. Its augment should simply allow you to cast on someone else.

**Comment by mlenser** [comment] 2020-05-24 08:00
> Personally, I don't think this spell should allow multitargets. Its augment should simply allow you to cast on someone else.

Heal should be able to be cast on multiple targets via augment (to simulate Mass Heal). I'm not sure how I lost that.

Why shouldn't we have mass spells?

**Comment by mlenser** [comment] 2020-05-24 08:02
Regenerate healing augment is halved if you target multiple creatures

**Comment by itamarcu** [comment] 2020-05-24 08:03
Off-topic but I'd like it if [Regenerate](https://www.kryxrpg.com/themes/spells/regenerate) and [Regrowth](https://www.kryxrpg.com/themes/spells/regrowth) were merged into a single spell (Life & Plants, unsure about Alteration) that had a target of touch. The augment would be adding targets (one per mana) or adding distance (120 feet, probably, as it would cost a whole mana point).

Thematically, they're pretty much exactly the same thing - regrowth and regeneration are almost synonyms, and I don't see why plants theme should grant you additional range, or be unable to regrow major organs (plants do that all the time!).

**Comment by mlenser** [comment] 2020-05-24 08:04
Please open off-topics in new issues. That is unrelated to this issue.

**Comment by mlenser** [comment] 2020-05-24 08:07
#### Minor
- **Themes**
  - **Life**
    - Heal adds an augment called Mass Heal. It was intended to be there, but somehow got lost on the way. [#281](https://github.com/mlenser/kryx-rpg-issues/issues/281)
  - **Plants**
    - Regrowth adds an augment called Mass Regrowth. It was intended to be there, but somehow got lost on the way. [#281](https://github.com/mlenser/kryx-rpg-issues/issues/281)

#### Patch
- **Themes**
  - **Alteration**
    - Regenerate healing augment is halved if you target multiple creatures [#281](https://github.com/mlenser/kryx-rpg-issues/issues/281)
  - **Life**
    - Regenerate healing augment is halved if you target multiple creatures [#281](https://github.com/mlenser/kryx-rpg-issues/issues/281)

**Comment by mlenser** [comment] 2020-05-24 08:07
Feel free to open a new issue about mass spells, though they are meant to emulate https://www.dndbeyond.com/spells/mass-heal

**Closed** 2020-05-24 08:07 UTC
Labels: Spells
