### ISSUE TITLE
Antitoxin should be removed or changed

### ISSUE THREAD

**Issue by itamarcu** [mlenser/kryx-rpg-issues#444] opened 2020-07-10 21:21 UTC
[Antitoxin](https://www.kryxrpg.com/concoctions/antitoxin) costs 2 mana to give the same effects as [Protection from Poison potion](https://www.kryxrpg.com/concoctions/protection-from-poison-potion).

Since the Protection from Poison is on the same level as Protection from Fire and such, I believe that Antitoxin should be changed.

**Comment by mlenser** [comment] 2020-07-11 05:53
Antitoxin aligned with Protection from Poison

**Comment by itamarcu** [comment] 2020-08-10 05:41
Why not remove one of these two options? They are identical and belong to identical themes, and the flavor is identical too.

**Comment by mlenser** [comment] 2020-08-10 06:08
Antitoxin removed as it is a duplicate of Protection from Poison Potion

**Closed by mlenser** 2020-08-10 06:08 UTC
