### ISSUE TITLE
Consider reducing the Stamina pool to 2 per level

### ISSUE THREAD

**Issue by Marcloure** [mlenser/kryx-rpg-issues#863] opened 2021-06-22 01:20 UTC
**Read the conclusion if you want a tl;dr of the issue**

Spells were nerfed repeatedly over the last few patches, which I'll consider fair. But then, now I have an issue with the amount of Stamina martials get. My reasoning:

- Consider a Gish that can choose between going maneuvers-only or spells-only. 
- Let's also use **Guiding Bolt** as our reference spell, since it is a spell attack and has the same hit chance of an attack.
- I'll consider **Distract** as our reference maneuver, since it has an effect similar to Guiding Bolt
- For our attack, I'll consider a d10 weapon as a middle value between d8 and d12. I'll also consider a Paladin, since it has the weakest  add-on damage (d4).

Guding bolt deals 5d6 (17.5) per mana + advantage on next attack.
Distract deals 1d8 (4.5) per Stamina + check for advantage + attack.

I'll not consider attack chance, since both has the same chance. The spreadsheet lists advantage on next attack as worth 2.46, and the Distract advantage has a 0.61 chance to apply (0.61 * 2.46 = 1.5).

--- 

#### 3rd level
- Considering what is listed above, Distract at 1 Stamina deals 1d8 (4.5) + 1.5 + 2d10kh1 (7.5) + 3 + 1d4 (2.5) = 19
- Guiding bolt at 1 mana deals 5d6 (17.5) + 2.46 = ~20

1 Stamina takes 1 out of 7 (14.2%) of a Stamina-only Paladin's pool. My suggestion would make it 1 out of 6 (16.66%).
1 Mana takes 1 out of 2 (50%) of a Mana-only Paladin's pool.

#### 5th level
- Distract at 2 Stamina deals 2d8 (9) + 1.5 + 2d10kh1 (7.5) + 3 + 1d4 (2.5) = 23,5
- Guiding bolt at 1 mana deals 5d6 (17.5) + 2.46 = ~20

2 Stamina takes 2 out of 11 (18.2%) of a Stamina-only Paladin's pool. My suggestion would make it 2 out of 10 (20%).
1 Mana takes 1 out of 4 (25%) of a Mana-only Paladin's pool.

#### 9th level
- Distract at 3 Stamina deals 3d8 (13.5) + 1.5 + 2d10kh1 (7.5) + 4 + 1d4 (2.5) = 29
- Guiding bolt at 2 mana deals 10d6 (34) + 2.46 = ~36.5

3 Stamina takes 3 out of 20 (15%) of a Stamina-only Paladin's pool. My suggestion would make it 3 out of 18 (16.66%).
2 Mana takes 2 out of 7 (28%) of a Mana-only Paladin's pool.

#### 13th level
- Distract at 4 Stamina deals 4d8 (18) + 1.5 + 2d10kh1 (7.5) + 5 + 2d4 (5) = 37
- Guiding bolt at 2 mana deals 10d6 (34) + 2.46 = ~36.5

4 Stamina takes 4 out of 29 (13,7%) of the Stamina-only Paladin's pool. My suggestion would make it 4 out of 26 (15.38%).
2 Mana takes 2 out of 10 (20%) of the Mana-only Paladin's pool.

#### 17th level
- Distract at 5 Stamina deals 5d8 (22,5) + 1.5 + 2d10kh1 (7.5) + 5 + 2d4 (5) = 41,5
- Guiding bolt at 3 mana deals 15d6 (34) + 2.46 = 55

5 Stamina takes 5 out of 38 (13,15%) of the Stamina-only Paladin's pool. My suggestion would make it 5 out of 34 (14.7%).
3 Mana takes 3 out of 13 (23%) of the Mana-only Paladin's pool.

---

### Conclusion

As you can see above, there are some level discrepancies. Of course, the levels where the Paladin increases its Maneuver limit but not its spell limit weights against the Spell-only Paladin. **At this point, the maneuver and the spell deal about the same damage, but you can use ~45% more maneuvers**

Now, at the 9th and 17th levels, when the paladin increases its mana limit, **spells deal about 20–25% more damage than maneuvers, but the Paladin can use twice as many maneuvers** (9th level: 6 maneuvers or 3 spells; 17th level: 7 maneuvers or 4 spells).

I believe this isn't right, so reducing the amount of maneuvers seems to close those ratios, specially at higher levels. It also makes the progression smoother, 2 stamina per level. I don't know if that would be enough, but would a good trimming, I believe.

Also, consider that I'm using a Paladin with d10 weapon. Another class with a d12 weapon and 2d6 extra damage, like the Ranger or Hexblade, would prefer the maneuver even more.

**Comment by Marcloure** [comment] 2021-06-22 01:49
You may also prefer to increase the mana-pool of gishes, that is also an option.

**Comment by itamarcu** [comment] 2021-06-22 06:10
Based on your data I think you're trying to solve the wrong problem.  The intention of mana vs stamina is that each point of mana is "worth" much more than stamina - giving higher burst damage even if lower overall consistent damage.

With the numbers you've shown, 1-mana Guiding Bolt deals almost exactly the same damage as 1-stamina Distract, which goes against what (I think) we want.  Giving the martial/gish less stamina won't help - they would still much rather spend half as many resources, for nearly equivalent damage per turn, unless the amount of stamina is drastically reduced.

Guiding Bolt does have some additional advantages over Distract:  long range (20m) and a radiant damage type. But still, it seems inferior to the maneuver.

I think a better solution would be to either decrease the base Paladin/martials damage (e.g. delaying the +1d4, removing fighting style) or increase the base Guiding Bolt/spells damage (e.g. literally increasing the spell's damage, or allowing the Paladin to apply extra damage on it too).

However, I'd also want to see this calculation in context of the expected DPR of every class.  19 damage on a maneuver seems

**Comment by mlenser** [comment] 2021-06-22 07:55
> Spells were nerfed repeatedly over the last few patches, which I'll consider fair.

"nerfed repeatedly"... What has actually happened:

- 4 mana spells are limited to 1/short rest (3/day)
- Spells and concoctions at 2, 3, 4, and 5 mana do 5, 10, 15, and 20 less damage value, respectively. 1 mana has not changed at all.
- Conditions are now considered to be more valuable than before, apply to concoctions, maneuvers, and spells.

Spellcasters are **_still_** by far the most useful classes when it comes to utility, AoE, CC, etc. Let's not pretend like that isn't the case. And their single target burst is incredibly strong, especially in the later tiers as they have more resources to work with.

_____________________________________

> The intention of mana vs stamina is that each point of mana is "worth" much more than stamina - giving higher burst damage even if lower overall consistent damage.

100% agreed. Mana and stamina serve very different roles. Martials are all about consistent damage while casters are about utility, burst, and CC.


________________________

## Comparison

If you're looking to compare stamina dice vs spells then use the same class and archetype. Then you can see an actual comparison of the two used on the same chasis. The comparison above attempts to show a caster vs gish, which we know starts in the gish/martial's favor via my spreadsheet:

![chart](https://user-images.githubusercontent.com/235857/122884992-f5c9ac80-d33e-11eb-8ed6-9d6fd006e7c9.png)
![chart (1)](https://user-images.githubusercontent.com/235857/122885005-f7937000-d33e-11eb-9753-ee6f94b0ef99.png)




Some of the assumptions provided are fundamentally flawed:

> Let's also use Guiding Bolt as our reference spell, since it is a spell attack and has the same hit chance of an attack.
> I'll consider Distract as our reference maneuver, since it has an effect similar to Guiding Bolt

This comparison is fundamentally flawed. Guiding Bolt has a range of 20m, deals radiant damage, and is not stopped by Soak.

- A hypothetical melee version would deal 6d6 instead of 5d6.
- Radiant damage ignores resistances to B/P/S which are relatively common
- Soak prevents ~0-3 damage per attack, depending on tier/creature.

>  I'll also consider a Paladin, since it has the weakest add-on damage (d4).

Paladins are one of the most defensive oriented archetype. That said, their d4 deals energy-type damage, not B/P/S so this is not impacted by soak or resistances.

> Guding bolt deals 5d6 (17.5) per mana + advantage on next attack.
> Distract deals 1d8 (4.5) per Stamina + check for advantage + attack.

A chance to get advantage is very different from an automatic effect. Guiding bolt will apply the advantage 100% of the time it hits. Distract will apply it ~50-70% of the time it hits. That's a huge difference.

> 2d10kh1 (7.5)

This is 7.15, not 7.5
![image](https://user-images.githubusercontent.com/235857/122881128-142da900-d33b-11eb-84a9-0b63d0876d2d.png)

> Distract at 1 Stamina deals 1d8 (4.5) + **1.5**

1.5 is damage value, not actual damage.

___________

## Conclusion

It has been known for a long time that casters scale up. They are less effective at pure damage at the lower tiers. This has not changed.

In regards to spells vs maneuvers then we should do a proper comparison using DPR. This style of math is misleading at best as it ignores many factors. A martial ranger vs caster ranger for example. Even then, I'm totally fine if the martial does a bit more than the caster (~5-10%) as the martial is much more limited in their utility, AoE, and CC options.

**Comment by mlenser** [comment] 2021-06-22 11:00
Brief comparison: Martial Paladin does ~5-10% more DPR, depending on the tier
![image](https://user-images.githubusercontent.com/235857/122913546-dd1ac000-d359-11eb-9a44-8f8af47e6218.png)

**Comment by mlenser** [comment] 2021-06-22 11:29
A 1 mana spell without any range or damage factors would do ~19.5 damage, or half on a failure, for ~15 damage value. So it bursts for ~15, 30, 45, 60, 75.

A GWF Paladin is doing between ~8.2-10.7 damage value at tier 1. Add on a maneuver and it's ~11.8-14.3.

So bursting seems about correct with martials approaching spell burst at level 4, but rather below at level 1-3.

**Comment by DalenWBrauner** [comment] 2021-06-22 11:36
I'm a bit confused by this statement:
> The comparison above attempts to show a caster vs gish,

When Marcloure is clearly using a Spells-only Paladin vs a Maneuvers-only Paladin. What did you mean by this?

I also think Shem had a wise interpretation of Marcloure's concern:
> I think you're trying to solve the wrong problem. [...] With the numbers you've shown, 1-mana Guiding Bolt deals almost exactly the same damage as 1-stamina Distract, which goes against what (I think) we want.

Now you've obviously poked some strong holes in that specific concern:
- Guiding Bolt has a range of 20m
- Guiding Bolt's radiant damage ignores resistances to B/P/S, which are relatively common
- Guiding Bolt's radiant damage is not stopped by Soak, which prevents ~0-3 damage per attack (depending on tier/creature)
- Guiding bolt will apply the advantage 100% of the time it hits, versus Distract's ~50-70% of the time it hits.

But I wanted to ask directly, just to be thorough: Are Distract and Guiding Bolt each (independently) at about the right power level, considering the cost of their resources?

**Comment by mlenser** [comment] 2021-06-22 11:41
> I also think Shem had a wise interpretation of Marcloure's concern

Marcloure's math is not accurate. See the math above. Any concluson based on it is not valid.

> But I wanted to ask directly, just to be thorough: Are Distract and Guiding Bolt each (independently) at about the right power level, considering the cost of their resources?

Guiding Bolt is slightly above expected damage value
![image](https://user-images.githubusercontent.com/235857/122918303-43561180-d35f-11eb-8897-87668c17de85.png)
Distract is below expected damage value
![image](https://user-images.githubusercontent.com/235857/122918387-5ec11c80-d35f-11eb-9f89-4b9330e034af.png)

Based on those expectations, these individual options are close enough to the guidelines.

But those individual options are just examples used to try to highlight a larger issue.

**Comment by DalenWBrauner** [comment] 2021-06-22 11:44
Thank you!

I understand the original concern's mathematical issues, but to me, there was still a "hunch" worth addressing for finality.

**Comment by mlenser** [comment] 2021-06-22 11:58
> there was still a "hunch" worth addressing for finality.

Feel free to make duplicates of the DPR sheet or power sheet to show how this is the case.

Some other damage related intangibles:
- Half caster can use their mana to buff their attacks with options like Flaming Weapon. Martials generally can't and their limited options are much less powerful
- Half casters can buff themselves or allies
- There is an assumption characters can be effective on all rounds. This doesn't take actual play into account where range or elevation likely matters. Half casters can use ranged spells when a normal martial might pull out a bow. Then you're comparing bow damage vs a ranged spell which are very different.

In addition to those, casters have other utility spells.

The question then becomes: "How much less damage should a half caster due compared to an equivalent martial?"

My gut says ~5-10% to make up for all of that.

**Comment by Marcloure** [comment] 2021-06-22 12:08
> Marcloure's math is not accurate. Any concluson based on it is not valid.

The only thing that is indeed wrong the the 2d10kh1 average, and that 0.35 difference shouldn't invalidate everything.

> Guiding bolt will apply the advantage 100% of the time it hits. Distract will apply it ~50-70% of the time it hits. That's a huge difference.

About "1.5 is damage value, not actual damage.", what is the difference between damage value and actual damage? Do you not add the condition damage value to the base damage?

> Martial Paladin does ~5-10% more DPR, depending on the tier

Does this table takes usage in consideration?

![Uploading image.png…]()

My point is not to change the damage, but the stamina pool for maneuvers. If that table doesn't consider the availability of maneuvers, then Martial Paladin does ~5-10% more damage and can use up to **twice as many** maneuvers at the limit.

**Comment by mlenser** [comment] 2021-06-22 12:39
> The only thing that is indeed wrong the the 2d10kh1 average, and that 0.35 difference shouldn't invalidate everything

The math you provided: fails to account for:
- fails to account for chance to hit
- fails to account for partial hits
- fails to account for soak
- fails to account for crits
- fails to account for opportunity attacks
- mixes damage with damage value.
- (intangibles mentioned above, but that's intangible).

My sheet takes those things into account and provided the numbers that I mentioned above:

> A 1 mana spell without any range or damage factors would do ~19.5 damage, or half on a failure, for ~15 damage value. So it bursts for ~15, 30, 45, 60, 75.
> 
> A GWF Paladin is doing between ~8.2-10.7 damage value at tier 1. Add on a maneuver and it's ~11.8-14.3.

**_Napkin math is not accurate_** and using it to make conclusions is a flawed method. This system is data driven, but the data must be as accurate as we can make it.

> My point is not to change the damage

Any concern based on math must use accurate math. If you think there is an issue then please show accurate math that shows it. Once that happens then we can figure out how it should be addressed, if at all (given the ~5-10% discussion).

> Does this table take usage in consideration?

That table is pure standard damage + burst from a spell or a maneuver. I'm unsure if the main issue is burst or DPR over a day so I've jumped between the two.

**Comment by mlenser** [comment] 2021-06-22 12:45
Another factor worth considering: There are a handful of spells that can be used with an attack. They deal more based damage and scale significantly better than martial options while still allowing full attacks. So if gishes want to damage and still attack, then these are great options:

![image](https://user-images.githubusercontent.com/235857/122926830-8c5e9380-d368-11eb-9750-f2f909f7bf57.png)

**Comment by Marcloure** [comment] 2021-06-22 13:02
> Napkin math is not accurate and using it to make conclusions is a flawed method. This system is data driven, but the data must be as accurate as we can make it.

I can not simulate a spreadsheet you've made over the years to make a single post, I can only provide insights to try to convince you to look into the matter. Gladly you didn't "math is wrong"-ignored me.

> That table is pure standard damage + burst from a spell or a maneuver. I'm unsure if the main issue is burst or DPR over a day

Well, the original divide was that spells provided burst while maneuver DPR over the day. This was changed over many patches, and now both martials and full casters deal about the same burst damage at very high levels. In the gish's case, it seems like the Spells-only is losing at both ends (lower burst _and_ DPR)?

**Comment by mlenser** [comment] 2021-06-22 13:31
> I can not simulate a spreadsheet you've made over the years to make a single post

You can make a duplicate of the spreadsheet. Or you can spend a bunch of time adding in all the factors. Not including all the factors is misinformation at best and can lead to inaccurate conclusions.

> now both martials and full casters deal about the same burst damage at very high levels

That's not true, at all. Casters provide more burst at all tiers without even accounting for AoE effects.

> In the gish's case, it seems like the Spells-only is losing at both ends (lower burst and damage over a day)?

Is this a rant post or a post that is meaningfully trying to understand how the system works and seeing if any adjustment is needed? If it's the former then I'll ignore it. If it's the later, please see the several posts above.

**Comment by Marcloure** [comment] 2021-06-22 13:42
> please see the several posts above

I don't understand, your posts above seem to support what I said. Your table shows that maneuvers deal more damage, which is fine, but you said you didn't consider usage. As the Paladin can use up to twice as many maneuvers than spells on a day, then it can also deal more damage over a day.

It's fine if maneuver's damage is better, that is ok, but I don't think maneuvers should both do more damage and be much more plentiful (twice as many). I am also fine if you can use more maneuvers, but I think the amount can be trimmed a bit (2 per level, instead of 2.25).

**Comment by mlenser** [comment] 2021-06-22 15:15
What is your concern?

- Spell only gishes do less burst than martials?
- Spell only gishes have less sustained damage over an adventure day?
- Both?

I believe neither is correct when specific spells are used and can show that once I know your concern.

**Comment by Marcloure** [comment] 2021-06-22 15:29
Both happening at the same time, specifically, the Paladin being able to use twice as many maneuvers when maneuvers aren't much weaker than spells. If I understood your table correctly, maneuvers deal 5–10% more burst damage and you can use them twice as many times. I think the usage should be tonned down a bit (not all the way down).

**Comment by mlenser** [comment] 2021-06-22 16:50
> Both happening at the same time, specifically

If the caster can produce better burst and sustain at the same time than a martial, then what is the role of a martial? What do they bring to the table?

**Comment by Marcloure** [comment] 2021-06-22 17:05
> If the caster can produce better burst and sustain at the same time than a martial

I'm not asking for this, you seem to be exaggerating my want. I'm _not_ saying that mana should be doubled or spell's damage increased. Spells could be better in bursting than maneuvers, maybe, but that is another discussion. What I'm stating is that a Paladin can **use maneuvers twice as many times as spells to deal around the same damage on each use.**

**Comment by mlenser** [comment] 2021-06-22 17:08
Please, let's focus on this issue, not solutions. We haven't established that there is an issue yet.

> I'm not asking for this

You just asked for it above? Let me ask again:

What is your concern?

- Spell only gishes do less burst than martial gishes?
- Spell only gishes have less sustained damage than martial gishes over an adventure day?
- Both at separate times?
- Both at the same time?

**Comment by Marcloure** [comment] 2021-06-22 17:14
It is "Both at the same time". Not sure if _all_ the time, but accordingly to your table, spells do deal less burst damage and can be used less than maneuvers.

Those strike spells seem to be an exception, but I don't think having a few very strong options justify the other spells.

**Comment by mlenser** [comment] 2021-06-22 17:22
So you want spellcasting gishes to be able to produce better sustained DPR over and an adventuring day and better burst than a martial, all on the same adventuring day?

Then I again ask: If the caster can produce better burst and sustain at the same time than a martial, then what is the role of a martial? What do they bring to the table?

**Comment by Marcloure** [comment] 2021-06-22 17:28
What? I did not say that. I do _not_ ask for the spell's damage to be increased, so burst would still favor maneuvers. I do _not_ ask you to double the mana pool, so damage over the day would still favor maneuvers.

What I said is that being able to use 2x as many maneuvers is too much. Maybe 1.8x or 1.6x or some other value may be more balanced.

**Comment by mlenser** [comment] 2021-06-22 17:31
Please, let's focus on this issue, not solutions. We haven't established that there is an issue yet.

> What? I did not say that.

Both at the same time means that the spellcaster can do more sustained damage and more burst damage in the same adventuring day.

If that is not what you mean then I'll ask again. What is your concern?

- Spell only gishes do less burst than martial gishes?
- Spell only gishes have less sustained damage than martial gishes over an adventure day?
- Both at separate times?
- Both at the same time?

**Comment by Marcloure** [comment] 2021-06-22 17:39
My concern is that spells both deal less damage _and_ has fewer uses. This concern does not mean that I want spells to both deal more damage _and_ have more uses. 

Spells could have better burst or more uses, one or the other, not both. However, I don't think that is needed too. Only a trimming of maneuver usage, not a complete reversal.

**Comment by mlenser** [comment] 2021-06-22 17:54
Please, engage with this exercise to establish roles between martial vs caster. Otherwise we should just stop as this is going no where.

Here is how I see the divide: 

## Half casters bring the following to the table
- Significantly better AoE
- Significantly better CC
- Significantly better Utility
- Better sustained damage by using spells like flaming weapon which add ~3 DPR in tier 1, ~6 DPR in tier 2, ~12 DPR in tier 3 and tier 4, and ~17 DPR in tier 5
- Ranged options to use when the enemy is out of range or on elevated terrain
- Better burst when using normal attacks + spell attack spells like Rising Phoenix, Telekinetic Charge, etc

## Martials bring the following to the table
- Consistent small effects that can be used regularly
- ?

____________

Have I missed something that martials do better?

What is your concern?

**Comment by Marcloure** [comment] 2021-06-22 18:21
> Better burst when using normal attacks + spell attack spells like Rising Phoenix, Telekinetic Charge, etc

Having these spells doesn't justify the others being worse. Fireball and Conjure Animals existing in 5e doesn't justify the bad options.

> **Martials bring the following to the table**
> Consistent small effects that can be used regularly
> ?

Other things are:
- Better burst damage (as per your table)
- Twice as many uses

Also, consider that if CC and damage result in the same damage value, than causing a CC is not an advantage over direct damage.

---

Again, I am fine if maneuvers deal more damage and have more uses per rest, but it should be this large a difference.

**Comment by mlenser** [comment] 2021-06-22 18:37
> Having these couple of spells doesn't justify the others being worse. Fireball and Conjure Animals existing in 5e doesn't justify the bad options.

The spells aren't worse, they just have different uses.

> Better burst damage (as per your table)

They don't have better burst damage. See Flaming Weapon, AoE, Rising Phoenix, and other similar options.

> Twice as many uses

That is covered in the first bullet "Consistent small effects that can be used regularly"

> Also, consider that if CC and damage result in the same damage value, than causing a CC is not an advantage over direct damage.

They don't.

____________

> I am fine if maneuvers deal more damage and have more uses per rest, but it shouldn't be this large a difference.

The "difference" in the screenshots above is the _average_ using immediate usage effects. That is not a real world scenario where a caster will use Flaming Weapon, AoE, Rising Phoenix, and its ranged options when it is unable to get in melee while a martial pulls out a bow.

If I were to actually calculate those things, spells would be significantly ahead.

Even if you just consider the ranged issue: In my experience this occurs regularly. Typically every 5th round of combat (usually the first round, when switching targets, or when enemies get on elevated terrain).

A bow does ~12 DPR for 2 actions and that is assuming the martial is Dex based. Compare that to a spell which does either 15 dmg + cantrip, 15x2 damage, or a big two action spell.

20% of the time is a lot of the time.

**Comment by Marcloure** [comment] 2021-06-22 18:47
All what you said is probvably be true, but that doesn't make maneuvers twice as bad as spells. In fact, it seems that maneuvers are better in some scenarios and worse in others. That is all good, but then why do maneuvers have 2x the uses per rest? This seems to be far too much considering that they aren't twice as bad.

**Comment by mlenser** [comment] 2021-06-22 19:00
> why do maneuvers have 2x the uses per rest? This seems to be far too much considering that they aren't twice as bad.

Maneuvers are things you can add on to normal attacks. Path to the Grave is a spell that can do the same.

Using simple math so it is easier to understand: Path to the Grave does 10.5+spellcasting ability, or ~14 damage on a hit. A maneuver does ~4.5 damage on a hit. A maneuver would have to use 3 stamina to be equivalent to 1 mana in this case.

## Tier 1

- Half caster adds ~12.5-13.5 damage on a hit
- Martial adds ~4.5 damage on a hit

## Tier 2

- Half caster adds ~13.5-14.5 damage on a hit
- Martial adds ~9 damage on a hit

## Tier 3

- Half caster adds ~28.5 damage on a hit (7d6+spellcasting)
- Martial adds ~13.5 damage on a hit

__________

When used like-for-like, spells are definitely twice as strong as maneuvers.

**Comment by itamarcu** [comment] 2021-06-22 19:13
Yes, the "attack spells" like Path to the Grave are a perfect example of mana vs stamina being balanced, for a Gish.  Higher burst damage but less overall/consistent damage fits the design intentions.

I think one problem brought up in this discussion is that many other spells, which don't scale with your base attack, seem weaker by comparison.  For example, 1-mana Ravage seems to deal only slightly more than Path to the Grave, and the latter only becomes better and better.  This means that caster gishes who pick these spells won't really feel like their damage or burst is any better than it would be if they'd been martial instead.

**Comment by Marcloure** [comment] 2021-06-22 19:21
That is an issue with Path to the Grave and similar spells. They are objectively better than other spells for gishes, and kinda force gishes to use them if they want to cast a spell to deal damage.

**Comment by mlenser** [comment] 2021-06-22 19:23
> I think one problem brought up in this discussion is that many other spells, which don't scale with your base attack, seem weaker by comparison.

When used to replace an attack, definitely. Replacing an attack should only be reserved for big aoe-type spells. Otherwise buffs that enhance your attacks, reactions that damage a creature back, attack-addon spells, etc are much better choices.
Single target spells are best used when out of range (or to trigger a big concentration save, per the current rules).

**Comment by Marcloure** [comment] 2021-06-22 19:29
> When used to replace an attack, definitely

I don't agree with this. You are saying that Guiding Bolt and Ice Spear is ok to be subpar because another better option exists (which are like 7 or 8 spells that do basically the same thing, so it's actually 1 spell with variations). I don't think this is a good way to look at this.

**Comment by mlenser** [comment] 2021-06-22 19:33
I have never said guiding bolt is subpar. I said it shouldn't be used to replace an attack. It should be used to replace a ranged attack (which it is).

**Comment by mlenser** [comment] 2021-06-22 20:06
Side note:

> like 7 or 8 spells that do basically the same thing, so it's actually 1 spell with variations

These spells are not the same. They are not carbon copies. They are far more varied than maneuvers.

**Comment by Marcloure** [comment] 2021-06-22 20:10
> I said it shouldn't be used to replace an attack. It should be used to replace a ranged attack (which it is).

Then most spells are only competitive if you are not in your best position? That isn't very encouraging. Like, most of the time you shouldn't be using damage spells besides Path to the Grave, only if you happen to find yourself in a bad position you should consider using Ice Spear or Recall Agony. I don't believe this should be the case, or at least, this isn't a full advantage over maneuver. Since then maneuvers are better if you are fighting on the conditions you are made to fight.

> These spells are not the same. They are not carbon copies. They are far more varied than maneuvers.

They are not 100% the same, but I doubt someone would expend their choices to have both Rising Phoenix and Gale Strike, for instance.

**Comment by mlenser** [comment] 2021-06-22 20:47
> Then most spells are only competitive if you are not in your best position? That isn't very encouraging.

...what? No one says:
- [insert RAW single target spell] is bad because my Ranger chose to use it instead of attacking
- aoe spell is bad because I targeted one creature
- cone is bad because I targeted one creature
- cantrip is bad because I used it instead of attacking

Use the right tool for the right purpose. Your whole premise is based on using the wrong tool and comparing it to a completely different use case's tool..


> They are not 100% the same, but I doubt someone would expend their choices to have both Rising Phoenix and Gale Strike, for instance.

The only thing they have in common is they are the same category (dash and attack). One deals more damage while the other pushed and prones. Completely different use case's.

At this point you're just ranting so I'm going to close this issue. There is no apparent issue when the right tool is used. This could possibly lead back to the spell strike discussion, but then we're in a new issue.

**Closed by mlenser** 2021-06-22 20:47 UTC
Labels: Class, Maneuvers

**Comment by Marcloure** [comment] 2021-06-22 21:05
> There is no apparent issue when the right tool is used

Of course there is. Even in the right situation (a melee Paladin targeting a creature beyond its reach), when spells perform better than maneuvers, it costs twice as much to cast a spell. In the optimal case for a maneuver (a melee Paladin fighting at melee), you can do it twice as much.

You seem to be saying that maneuvers and spells are balanced because their use cases and damage are balanced, and that may be true, but you are not considering that you can use twice as many maneuvers. Like, maneuvers are good in melee, spells at range, so why can you use that many more maneuvers if they aren't worse?
