### ISSUE TITLE
Weapon-Style Feats Locked Behind Themes

### ISSUE THREAD

**Issue by Lamorak11** [mlenser/kryx-rpg-issues#174] opened 2020-05-07 22:51 UTC
I don't think weapon and fighting-style feats should be locked behind themes. There are many different variations that are not supported by this restriction and its an unnecessary theme tax in a lot of cases if you just want the theme for the one feat. I think many of them should become general feats.
 
A couple examples:
- **Born to the Saddle**: Anyone can become a skilled rider. There's no reason that a mage or druid couldn't do this. This should definitely be general.
- **Mounted Combat**: Mounted combat is no more relevant to the vanguard theme than it is to the skirmish theme. Mounts historically were used in multiple capacities in war. There is no reason a more scout-themed character couldn't have easy access to this feat.
- **Cleave, Polearm Master, Pugilist, Dual Wielder**: I don't think there's a terribly compelling reason why you couldn't have a skirmishing-focused polearm user, or a two-weapon wielding vanguard, and of course you can, but if you weren't intending on having your fighting style based around the skirmish or vanguard styles respectively then you have been forced to select a theme that has no real bearing on your character. Cleave is perhaps the only one that might deserve to stay where it is, due to the comparative inelegance and savagery that doesn't seem a good fit for the other themes.

If moving them to general isn't satisfactory, then perhaps having them exist in multiple themes could be a good compromise.

**Comment by Lamorak11** [comment] 2020-05-07 22:52
I think that in a way, this also highlights one of the problems with the marksmanship theme. There is clearly a difference between it and the other martial themes. Marksmanship wholly contains two entire styles of combat (ranged and throwing) with a small selection of similar weapons, whereas the other themes have much more of a blurring of the lines and interchangeability. 

The trouble is, is that those same blurred lines make it difficult to properly focus a theme like vanguard, which is probably as nebulous as marksmanship is over-focused. Its a hard balance to strike, but I think we all know that this dissatisfaction is more to do with an underlying problem with the martial themes, and these issues more of a symptom. 

The more I think about the Martial themes, the more dissatisfied I am with it, but I'm struggling to come up with an elegant solution, but that's a conversation for a different thread.

**Comment by Paulorpribeiro** [comment] 2020-05-08 10:32
I think there actually should be one theme for each fighting style. If you wanna mix and match, you should choose both themes. I usually see fighting styles as cantrips, in the sense that you need to commit resources to learn them. You don't complain that you have to pay a tax and choose the teleportation theme to get a teleportation cantrip. It just feels differently because there are many cantrips and just a handful of styles

**Comment by Paulorpribeiro** [comment] 2020-05-08 10:38
Sorry, I mean feats, not fighting styles. We could maybe make characters choice of fighting styles restricted to the themes, but that is a bit too much. Feats locked behind Themes is ok imo

**Comment by Lamorak11** [comment] 2020-05-08 12:12
> You don't complain that you have to pay a tax and choose the teleportation theme to get a teleportation cantrip. It just feels differently because there are many cantrips and just a handful of styles

I disagree. Weapon styles are nothing like cantrips. Almost all cantrips are specific to their theme, because they are thematic magical effects and so it's obvious that a minor telekinesis cantrip requires the telekinesis theme - you couldn't argue that a character could obtain minor telekinesis from the Fire theme. When a cantrip could work in multiple themes, that has been done, and they exist in multiple themes, albeit sometimes with a different skin. 

There is nothing about skirmish or vanguard that really suggests a certain weapon-style. You can easily argue that a character could learn dual wielder from the vanguard theme. 

If we were to compare to compare weapon-style feats to anything, it would be more like an advanced or expert weapon/skill proficiency. I mean, the ability to use a weapon is a skill, in the most literal sense.

**Comment by DalenWBrauner** [comment] 2020-05-08 13:11
...Except Magic is Magic- it's an inherently superhuman power granted to
you by a theme. No Martial theme is that way by design- so while I can't
imagine casting Fireball without having learned how to use Fire Magic,
isn't it conceivable that a warrior could learn _any_ maneuver without
knowing its prerequisite theme?

So perhaps that's the criteria we need to use. You couldn't have learned
how to deflect blows for your allies with your shield unless you've studied
how to use Shields effectively. You couldn't have learned how to fire
multiple arrows at once unless you've properly studied the Bow. A warrior
might be able to use multiple attacks per turn with _any_ weapon, but
couldn't learn how to cleave with a greatsword unless you've properly
studied Heavy Weapons. (Not that those are good names for themes.)

Literally the problem we have is: "What is the concept of a Martial Theme?
How is it defined?"

>

**Comment by Lamorak11** [comment] 2020-05-08 13:48
Dalen, you've pretty much summed up my misgivings with the whole martial theme system.

**Comment by Lamorak11** [comment] 2020-05-08 14:33
So I've been talking with one of my players and throwing some ideas around and I think I've come up with an interesting (if currently rough/ barebones) concept for how to deal with weapon styles that I think could fix some of our problems with the martial themes and weapon-based maneuvers and feats (in particular marksmanship). 

So, the idea is that ultimately, proficiency and mastery of weapons is closer to a basic skill or proficiency for a character than anything you should find in a theme. You wouldn't find a feat that gave proficiency in polearms in a theme - that's why weapon proficiencies are baked into the classes at first level, like skills. I think that you probably shouldn't have to have a specifically flavoured theme to learn a basic set of weapon-style based feats and maneuvers. 

My idea is thus:

Add a new set of options to the "Skilled" feature at 3rd level and every 3 levels thereafter which allows you to improve a proficiency with a specific weapon type (polearms, great weapons, light weapons, throwing weapons, ranged weapons, one-handed weapons etc) to "Master" level (purposefully not "expertise" due to the implications of increasing proficiency modifier by 1.5).

Becoming a "Master"

**Comment by DalenWBrauner** [comment] 2020-05-08 14:47
@Lamorak11 for some reason I don't see your most recent comment on the site, but it landed in my inbox- do you mind reposting it? It doesn't look like GitHub deleted it or anything- maybe it's hiding bc the issue was closed...?

**Comment by Lamorak11** [comment] 2020-05-08 14:51
So I've been talking with one of my players and throwing some ideas around and I think I've come up with an interesting (if currently rough/ barebones) concept for how to deal with weapon styles that I think could fix some of our problems with the martial themes and weapon-based maneuvers and feats (in particular marksmanship).

So, the idea is that ultimately, proficiency and mastery of weapons is closer to a basic skill or proficiency for a character than anything you should find in a theme. You wouldn't find a feat that gave proficiency in polearms in a theme - that's why weapon proficiencies are baked into the classes at first level, like skills. I think that you probably shouldn't have to have a specifically flavoured theme to learn a basic set of weapon-style based feats and maneuvers, and that this is equally holding the flavour of the themes back. 

My idea is thus:

Add a new set of options to the "Skilled" feature at 3rd level and every 3 levels thereafter which allows you to improve a proficiency with a specific weapon type (polearms, great weapons, light weapons, throwing weapons, ranged weapons, one-handed weapons etc) to "Master" level (purposefully not "expertise" due to the implications of increasing proficiency modifier by 1.5).

Becoming a "Master" Thrower does nothing except give you access to the Throwing Mastery (which is functionally a very small, specific theme, and could be called a theme I suppose). Within the Throwing Mastery are any feats and maneuvers that are specifically based on the throwing style, allowing any charactet to benefit from a weapon style provided they are at first proficient in the weapon type.

----

An issue I can see: this does reduce the number of skills most martial characters will obtain, but seeing as most characters are going to have a maximum of two weapon styles, this will only reduce their total "Skilled" feature skill choices from 6 to 4 or 5.

It also gives martials what could be considered a free theme, but I think this change could open the way for more flavourful martial/mundane themes, as now Weapon-Style is no longer a factor.

This might need a slight adjustment to how starting weapon proficiencies work, but nothing major, maybe just splitting some classes proficiencies into their types instead of just "simple and martial).

**Comment by mlenser** [comment] 2020-05-08 15:10
> I don't think weapon and fighting-style feats should be locked behind themes.

The goal of the sytsem is that everything is in a theme, so that's at odds with this view.

______________

> I think there actually should be one theme for each fighting style.

We pretty much have this:
- Marksmanship: Archery
- Protection: Defense/Protection
- Skirmish: Dueling/TWF
- Vanguard: Great Weapon Fighting

**Comment by Lamorak11** [comment] 2020-05-08 15:16
> The goal of the sytsem is that everything is in a theme, so that's at odds with this view.

Not everything. That's what I'm saying, proficiencies and skills are not a part of the theme system, and for a good reason - they are too general. Any character could have them.

What I'm arguing is that weapon styles, just like weapon proficiencies, do not belong in themes. They are too generalist to be in themes, or conversely if they are the only thing in that theme (marksmanship) they become way too focused on something that lacks any real flavour.

Therefore they should be moved to the skill and proficiency system.

**Comment by mlenser** [comment] 2020-05-08 15:20
There are many systems that use skill systems for weapons and I somewhat have dreams for such a system, but that system is nothing like 5e. If you have a concrete proposal for ripping out the whole weapon system and replacing it then I'm ears, but that's completely different.
Characters improve through feats - that's how it is intended. Feats aren't taxes, they are improvements.

Themes are playstyles. Vanguard is the playstyle that is on the frontline dishing out damage in the fray. That does not match with archery, shields, and many other styles. Greataxe, Greatsword, etc fit that model. TWF is somewhat in the same vein, but it's much much more about maneuverability, hence the Skirmish theme.

**Comment by Lamorak11** [comment] 2020-05-08 15:29
> Characters improve through feats - that's how it is intended. Feats aren't taxes, they are improvements.

Nowhere here have I suggested removing feats or that the style feats were taxes. I said that having to take a theme that has nothing to do with your character concept to access a weapon style feat is a tax. 

I'm suggesting an alternate way to reach weapon style feats which uses a system closer to the skill and proficiency system you have developed. 

> Vanguard is the playstyle that is on the frontline dishing out damage in the fray. That does not match with archery, shields, and many other styles. Greataxe, Greatsword, etc fit that model. TWF is somewhat in the same vein, but it's much much more about maneuverability, hence the Skirmish theme.

I'm sorry I just don't agree. The fact that many maneuverable characters that use two weapons doesn't actually intrinsically link the two. A heavily armoured dwarf welding two hammers should have nothing to do with the skirmish theme. A character like Oberon from GoT uses a spear, and he is an archetypal skirmishers type fighter. 

The themes suggest a playstyle. A fighting style _is not_ a playstyle.

**Comment by Marcloure** [comment] 2020-05-08 15:48
Then I believe themes should suggest fighting styles more than playstyles. You pick Water as a caster because you want that style of spell, but you can be a baster or a support Water mage. You pick Two Weapon fighting because you want this style, whether you are a skirmisher or a dwarf rager.

Anyway, I feel like we already had a discussion like this when we divided Warfare. Either we make weapon-specific themes (spear, heavy, shield, sword, axe, hammer, archery), or generic themes that can kinda fit with any weapon. After playing Ironsword, I kinda like weapon-specific themes, but at the same time it would limit what a character can wield properly.

**Comment by mlenser** [comment] 2020-05-08 15:57
> A heavily armoured dwarf welding two hammers should have nothing to do with the skirmish theme.

You've made a case that TWF belongs in both vanguard and skirmish. I'll solve that.

But putting it in general feats makes it available to everyone, including protection fighters or archers. And general feats will go away as much as possible.

**Comment by Lamorak11** [comment] 2020-05-08 16:50
> Then I believe themes should suggest fighting styles more than playstyles. You pick Water as a caster because you want that style of spell, but you can be a baster or a support Water mage. You pick Two Weapon fighting because you want this style, whether you are a skirmisher or a dwarf rager.

Yes, I have noticed that themes like skirmish and vanguard are the only themes based around how you play, rather than what you do. Judging by the success of the other themes and the problems we are having with those two, I think a move towards fighting style or weapon-style themes is probably the way to go.

> Either we make weapon-specific themes (spear, heavy, shield, sword, axe, hammer, archery), or generic themes that can kinda fit with any weapon. After playing Ironsword, I kinda like weapon-specific themes, but at the same time it would limit what a character can wield properly.

I think a bit of a compromise could work - fighting style themes that have a broader identity than weapon types. You could have: Two-weapon fighting, Great-weapon Fighting, (and/or) Polearm Fighting, Duelling, Protection (side note: a more flavourful name could be "Bulwark"), Mounted Combat, Marksmanship, (and/or) Throwing, Vanguard (the aggressive/ assault parts of vanguard that stay), Skirmish (the parts of skirmish that stay).

> There are many systems that use skill systems for weapons and I somewhat have dreams for such a system, but that system is nothing like 5e. If you have a concrete proposal for ripping out the whole weapon system and replacing it

I would love such a system too. I might make it a pet project of mine.

> You've made a case that TWF belongs in both vanguard and skirmish. I'll solve that.

I believe I've made a case for polearm master being in skirmish at the very least. Great-weapon fighting may not belong in skirmish, but I think that polearms could be and have been used very effectively by skirmish-focused fighters such as Oberyn from GoT and Monk-type characters with quarterstaves.

**Comment by mlenser** [comment] 2020-05-08 17:26
> I think a move towards fighting style or weapon-style themes is probably the way to go.

Try to map it out. I've done it for monsters. Weapons cover ~20% of all maneuvers. It's such a narrow way to distribute them and not condusive to making actual choices, but simply choosing a theme and then taking every maneuver possible in it.

>  I think that polearms could be and have been used very effectively by skirmish-focused fighters such as Oberyn from GoT and Monk-type characters with quarterstaves.

We can't take one example and hold it up as the reason to do something. Oberyn is a polearm user who happened to take Skirmish. Skirmish is not a typical choice for polearm users. Polearm users are typically slower moving and moving with formation.

**Comment by DalenWBrauner** [comment] 2020-05-08 18:00
Remember what I said before about this argument being entirely about the
definition of a theme?

Suppose we defined a Theme as "A prerequisite field of study (or
understanding) for a character to obtain certain abilities." That makes
sense for casting- you have to understand how to wield Fire Magic before
you can fling a Fireball.

Let's translate this to Martial Themes. Each Martial Theme becomes a
"Prerequisite field of study or understanding." Suddenly, vanguard and
skirmish make no sense- they're not _fields of study_, they're
_playstyles_. They're not groupings of maneuvers you would _learn_
together, but groupings of maneuvers you would _use_ together.

It flips our idea of what makes a good Martial Theme on its head.
Marksmanship is now no longer the black sheep because it doesn't fit- it's
now the black sheep because it is the paragon of what Martial themes should
be. You study how to use bows, how to aim with them, how to load and fire
them while moving, and so on.

This takes the opposite approach than Lamorak suggested, and for Kryx's
reasoning- the Themes system is dynamic, robust and interesting! Weapon
proficiencies, by comparison, are instead just flat yes/nos baked into a
class. Let's use Themes for this instead.

To take this to its full potential, this *could* imply that things like
Fighting Styles and Weapon Proficiencies become a part of Themes, rather
than classes... but before I get ahead of myself, let's look at some
potential examples of this way of thinking. Of course, I mean example
themes:

- Marksmanship:
The study of ranged weapons such as Bows, Crossbows and Slings.
- Bulwark:
The study of mastering Shields, not just for personal defense, but for
formations, defending others, deflecting attacks, and so on.
- Swordplay:
The art of Fencing, Swashbuckling, Samurai and Knightly combat. The
practice of using the sword for everything- offense, defense and strategy.
- Footwork:
The practice of positioning and evasion, of putting yourself precisely in
or out of a weapon's reach at just the right moment.
- Brawl:
Sometimes the best teacher is experience. The "art" of improvised weaponry,
opportunistic attacks, grapples, and withstanding heavy blows.
- Full Body:
The art of using only your body as a weapon- understanding where to strike,
the practice of swift strikes and counterattacks, and the defensive stunts
necessary to take on other weapons.
- Deceit:
The knowledge of every deceptive tactic in the book to get the edge of your
opponent. Backstabs, tendon slices, sand-in-your-eyes, the works.
- Beast:
The innate tendency to use wild, animalistic swipes, blows, strength,
senses and will to overpower your opponents.
- Heavy Melee (name pending):
The practice of Greatswords, Greataxes and Hammers- anything that takes
substantial muscle, timing, and probably 2 hands to net devastating blows.
Cleaves, armor breaks, and unique (but weaker) defensive tactics are
learned through this practice.

And so on. These are just examples of course, and I would prefer they be
made into mincemeat so that we can come out with something refined in the
end.

What are your guys' thoughts on this definition of themes: "A prerequisite
field of study (or understanding) for a character to obtain certain
abilities" ?

**Comment by mlenser** [comment] 2020-05-08 18:34
Combining earth and vanguard into one "great weapons" theme is a recipe for a 20-30 maneuver theme while other themes have 5-10.

I'm not sure how clear I can be about this: themes are not based on weapons. It is such an incredibly narrow way of allocating options that simply doesn't work.

**Comment by mlenser** [comment] 2020-05-08 18:41
For suggestions: please map out a significant portion of maneuvers. Doing so will help you form better suggestions.

**Comment by DalenWBrauner** [comment] 2020-05-08 19:11
If that's not the standard/definition we want to build Themes against, then
I think we need to come to some agreement on what *is*, before we can
discuss how a distribution of Themes and Maneuvers can meet that definition
in a satisfactory way.

Or is the goal simply to have meaningful choices between and within Themes
for Martial classes, by whatever sane means necessary?

**Comment by mlenser** [comment] 2020-05-08 19:13
Looking at definitions and words is one small aspect of it. Seeing how it is laid out based on those definitions is where the conversation gets meaningful and interesting. Without the second part it's just a thought in your head that someone else perceives being executed totally differently.

**Comment by DalenWBrauner** [comment] 2020-05-08 20:10
I'm just trying to tackle the overarching problem at different angles. If
we can find any common threads between what we would like to see from
martial themes, rather than just the things we dislike about how they're
set up currently (and in propositions), we're a lot more likely to come up
with a well-received solution when we take the time to pen out how feats
and maneuvers should be distributed.

But right now I only see dissatisfaction:
- Attempting to categorize all existing feats into specific themes may
induct an unnecessary "theme tax" if not distributed well
- We have a mix of "too narrow" and "too broad" martial themes, without a
strong idea of what a "just right" martial theme might look like
- Not all maneuvers fit cleanly into existing non-martial themes, and some
that do seem odd to exist only in those themes

And this is a little difficult to translate into a list of goals:
- Ensure feats are accessible to characters who could reasonably obtain
them (Wizards riding Horseback)
- Ensure that feats all have a home in some theme or another (why?)
- Ensure that martial classes have interesting and meaningful choices to
make when choosing between which themes to learn
- Ensure that martial classes have interesting and meaningful choices to
make when choosing feats/maneuvers from the themes they know (we need more
maneuvers)
- Ensure we have obvious or solid concepts for each martial theme (so that
we can minimize debate as to whether a feat/maneuver belongs in a given
theme) (so that we can better conceptualize new maneuvers that would fit
that theme)
- Ensure maneuvers are accessible to all martial classes that could
reasonably learn them

I'd love to just build a fleshed-out example. But if we're not on the same
page as to what goals it should be achieving, then any and all designs are
going to be flawed from the start, and we're pretty unlikely to agree on
why.

**Comment by mlenser** [comment] 2020-05-08 20:18
People understand things differently. It appears you understand things more at a theoretical level. I, on the other hand, need to analyze things heavily. I need to see it executed. Talking words and definitions, while important, generally comes after the analysis, for me.

**Comment by mlenser** [comment] 2020-05-08 20:22
> Ensure feats are accessible to characters who could reasonably obtain them (Wizards riding Horseback)

I don't particularly agree with this goal or several other ones started on the first post of this issue. Casters are simply not expert horseriders. That's not their thing. Gishes and martials? Ya.

> Ensure we have obvious or solid concepts for each martial theme (so that we can minimize debate as to whether a feat/maneuver belongs in a given
theme) 

I believe this will be the biggest struggle. For me I'm still stuck on maneuvers somewhat belonging in themes like earth and air. Characters who take air shouldn't have to take another theme like Skirmish as those maneuvers should be available in Air as they definitely fit the theme.

**Comment by DalenWBrauner** [comment] 2020-05-08 21:09
Oh lord, I just saw how all of my email replies look. I gotta stop doing that...

> People understand things differently. It appears you understand things more at a theoretical level. I, on the other hand, need to analyze things heavily. I need to see it executed. Talking words and definitions, while important, generally comes after the analysis, for me.

Fair enough :) I'll try to lean into more concrete terms and examples.

> I believe this will be the biggest struggle. For me I'm still stuck on maneuvers somewhat belonging in themes like earth and air.

Agreed

> Characters who take air shouldn't have to take another theme like Skirmish as those maneuvers should be available in Air as they definitely fit the theme.

Conceptually, I agree, but I think you're walking into a minefield. Maybe we can both agree that evasive maneuvers make sense in air, maybe we don't. Maybe fluid knife movements belong in Water, maybe Blood, maybe neither. This is because we're lacking in this department:

> - Ensure we have obvious or solid concepts for each martial theme

But in this case, it's for the "martial" part of an otherwise mostly-magical theme. We agree on what an Air Theme looks like for spells, because it's literally "Magic that heavily uses or involves air". But we might not be able to agree on what that looks like for maneuvers. If maneuvers had magical properties, then there would be no debate, but they are expressly forbidden from doing so. The only thing then left to qualify is whether they're "evocative enough" of a Theme, and I think that's a lot harder to get right.

(Even Alchemy, despite not being magic, is always utilizing the core theme concept directly, rather than being evocative of it. There's no doubt what Theme a Healing Potion or a Fire Bomb belong to.)

But here I am, closing the loop all the way back to the start of #156. I'll try to see if I can come up with more concrete suggestions before writing so much- at this point I can't tell if the whole community is talking in circles or just me.

**Comment by DalenWBrauner** [comment] 2020-05-08 21:12
Yeah, actually, I'd like to apologize for how much text I wasted just rehashing exactly what was in #156. I really ought to have re-read it at least one more time.

**Comment by Paulorpribeiro** [comment] 2020-05-08 21:54
I think Github should be reserved for more fleshed out ideas while discord for more theoretical/design board discussions. I like both ways of trying to improve the system, but if we mix the two, like has been said, makes it harder to achieve agreement on anything and we run in circles

**Comment by Lamorak11** [comment] 2020-05-08 22:51
> I think Github should be reserved for more fleshed out ideas while discord for more theoretical/design board discussions. I like both ways of trying to improve the system, but if we mix the two, like has been said, makes it harder to achieve agreement on anything and we run in circles.
I'd sugest opening a "Martial theme issue" channel on discord.

Seconded, I didn't actually know about the discord so I'm happy to take these discussions there.

**Comment by Lamorak11** [comment] 2020-05-08 23:31
> Casters are simply not expert horseriders. That's not their thing. Gishes and martials? Ya.

My mum is an expert horse rider. Weird that I don't remember her telling me about the weapons and combat training that came with it, lol.

All joking aside, historically speaking in feudal medieval times many people were able to ride horses, and much of the noble class could ride with some skill. As in a fantasy setting a noble is just as likely to be a mage as a knight, I think that it is quite reasonable to expect that a skilled rider could conceivably be from any class. You could be an excellent rider _before you even had a character class_.

But in case you're unconvinced, a few examples of mounted casters:
- Gandalf!
- Fire Emblem: Dark Fliers, Valkyries and more
- Warhammer: a bunch of examples, high elf mages come to mind
- there's a 3rd party mounted caster feat for Pathfinder 
- remember that a mount isn't just a horse - and their are plenty of casters in fiction and in games like warcraft that ride mythical creatures. Dragons are a favourite.

Honestly, I very much doubt it will come up in one of my games, and if it did, I'd just let them take the feat. But for verisimilitude, any character should be capable of becoming an expert rider. It's just common sense.

**Comment by Paulorpribeiro** [comment] 2020-05-09 02:13
I agree with making born to saddle a generic feat (I think some feats should be generic, like tough,  not many though). I think it solves at least this problem.

**Comment by mlenser** [comment] 2020-05-12 18:22
> If moving them to general isn't satisfactory, then perhaps having them exist in multiple themes could be a good compromise.

Now that themes are opened up and some moved to multiple themes I think the main remaining issues are the Mounted feats. If you feel there is another theme they'd fit in let me know @Lamorak11

**Comment by mlenser** [comment] 2020-05-12 18:50
Added Born to the Saddle and Mounted Combatant to the Beast theme

**Comment by mlenser** [comment] 2020-05-12 19:06
Closing. I can reopen if we think something was missed. The main goal of general feats is outside the goals of the system so I tried to make some options more available. Let me know if any more should be made more available.

**Closed by mlenser** 2020-05-12 19:06 UTC
